Student/urls.py
from django.urls import path
from .student_views import student_render_pdf_view,student_view_result

app_name='Student'

urlpatterns = [
    # path('pdf2/',CustomerListView,name="exam_list_view"),
    path('pdf2/pdf/<id>',student_render_pdf_view,name="exam_card_view"),
    path('',student_view_result,name="transcript_view"),
]

school_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
# from Student.urls import render_pdf_view
from Student import views, hod_views, staffviews, student_views, admin_views
from Student.EditResultViewClass import EditResultViewClass
from Student.admin_views import delete_hod
from school_management import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    # path("home",views.home),
    path('accounts/',include("django.contrib.auth.urls")),
    path('',views.showLoginPage,name="show_login"),
    path('doLogin',views.doLogin,name="dologin"),
    path('get_user_details',views.GetUserDetails,name="get_user_details"),
    path('logout_user',views.logout_user,name="logout_user"),
    path('admin_home',hod_views.admin_home,name="admin_home"),
    path('add_staff',hod_views.add_staff,name="add_staff"),
    path('add_staff_save',hod_views.add_staff_save,name="add_staff_save"),
    path('add_course', hod_views.add_course,name="add_course"),
    path('add_course_save', hod_views.add_course_save,name="add_course_save"),
    path('add_student', hod_views.add_student,name="add_student"),
    path('add_student_save', hod_views.add_student_save,name="add_student_save"),
    path('add_subject', hod_views.add_subject,name="add_subject"),
    path('add_subject_save', hod_views.add_subject_save,name="add_subject_save"),
    path('manage_staff', hod_views.manage_staff,name="manage_staff"),
    path('manage_student', hod_views.manage_student,name="manage_student"),
    path('manage_course', hod_views.manage_course,name="manage_course"),
    path('manage_subjects', hod_views.manage_subjects,name="manage_subjects"),
    path('edit_staff/<str:staff_id>', hod_views.edit_staff,name="edit_staff"),
    path('update_student_units/<str:id>', hod_views.update_student_units,name="update_student_units"),
    path('edit_staff_save', hod_views.edit_staff_save,name="edit_staff_save"),
    path('edit_student/<str:student_id>', hod_views.edit_student,name="edit_student"),
    path('edit_student_save', hod_views.edit_student_save,name="edit_student_save"),
    path('edit_subject/<str:subject_id>', hod_views.edit_subject,name="edit_subject"),
    path('edit_subject_save', hod_views.edit_subject_save,name="edit_subject_save"),
    path('edit_course/<str:course_id>', hod_views.edit_course,name="edit_course"),
    path('edit_course_save', hod_views.edit_course_save,name="edit_course_save"),
    path('manage_session',hod_views.manage_session,name="manage_session"),
    path('add_session_save',hod_views.add_session_save,name="add_session_save"),
    path('check_user_email',hod_views.check_user_email,name="check_user_email"),
    path('check_username',hod_views.check_username,name="check_username"),
    path('check_subject_code',hod_views.check_subject_code,name="check_subject_code"),
    path('student_feedback_msg',hod_views.student_feedback_msg,name="student_feedback_msg"),
    path('staff_feedback_msg',hod_views.staff_feedback_msg,name="staff_feedback_msg"),
    path('student_feedback_msg_replied',hod_views.student_feedback_msg_replied,name="student_feedback_msg_replied"),
    path('staff_feedback_msg_replied',hod_views.staff_feedback_msg_replied,name="staff_feedback_msg_replied"),
    path('student_leave_reply',hod_views.student_leave_reply,name="student_leave_reply"),
    path('student_approved_leave/<str:leave_id>',hod_views.student_approved_leave,name="student_approved_leave"),
    path('student_disapproved_leave/<str:leave_id>',hod_views.student_disapproved_leave,name="student_disapproved_leave"),
    path('staff_leave_reply',hod_views.staff_leave_reply,name="staff_leave_reply"),
    path('staff_approved_leave/<str:leave_id>',hod_views.staff_approved_leave,name="staff_approved_leave"),
    path('staff_disapproved_leave/<str:leave_id>',hod_views.staff_disapproved_leave,name="staff_disapproved_leave"),
    path('admin_view_attendance',hod_views.admin_view_attendance,name="admin_view_attendance"),
    path('admin_get_attendance_date',hod_views.admin_get_attendance_date,name="admin_get_attendance_date"),
    path('admin_get_attendance_student',hod_views.admin_get_attendance_student,name="admin_get_attendance_student"),
    path('admin_profile',hod_views.admin_profile,name="admin_profile"),
    path('save_update_student_units',hod_views.save_update_student_units,name="save_update_student_units"),
    path('get_unregistered_student_units',hod_views.get_unregistered_student_units,name="get_unregistered_student_units"),
    path('admin_profile_save',hod_views.admin_profile_save,name="admin_profile_save"),
    path('admin_send_notification_student',hod_views.admin_send_notification_student,name="admin_send_notification_student"),
    path('admin_send_notification_staff',hod_views.admin_send_notification_staff,name="admin_send_notification_staff"),
    path('send_student_notification',hod_views.send_student_notification,name="send_student_notification"),
    path('send_staff_notification',hod_views.send_staff_notification,name="send_staff_notification"),
    path('download_registered_students',hod_views.download_registered_students,name="download_registered_students"),
    path('get_registered_students',hod_views.get_registered_students,name="get_registered_students"),
    path('student_pdf_view',hod_views.student_pdf_view,name="student_pdf_view"),
    # path('datatable',hod_views.datatable,name='datatable'),

    # staff url
    path('staff_home', staffviews.staff_home, name="staff_home"),
    path('staff_take_attendance', staffviews.staff_take_attendance, name="staff_take_attendance"),
    path('staff_update_attendance', staffviews.staff_update_attendance, name="staff_update_attendance"),
    path('get_students', staffviews.get_students, name="get_students"),
    path('get_student', staffviews.get_student, name="get_student"),
    path('registered_units', staffviews.registered_units, name="registered_units"),
    path('get_registered_units', staffviews.get_registered_units, name="get_registered_units"),
    path('unit_pdf_view', staffviews.unit_pdf_view, name="unit_pdf_view"),
    path('save_attendance_data', staffviews.save_attendance_data, name="save_attendance_data"),
    path('get_attendance_date', staffviews.get_attendance_date, name="get_attendance_date"),
    path('get_attendance_student', staffviews.get_attendance_student, name="get_attendance_student"),
    path('save_updateattendance_student', staffviews.save_updateattendance_student, name="save_updateattendance_student"),
    path('staff_apply_leave', staffviews.staff_apply_leave, name="staff_apply_leave"),
    path('staff_apply_leave_save', staffviews.staff_apply_leave_save, name="staff_apply_leave_save"),
    path('staff_feedback', staffviews.staff_feedback, name="staff_feedback"),
    path('staff_feedback_save', staffviews.staff_feedback_save, name="staff_feedback_save"),
    path('staff_profile',staffviews.staff_profile,name="staff_profile"),
    path('staff_profile_save',staffviews.staff_profile_save,name="staff_profile_save"),
    path('staff_fcmtoken_save',staffviews.staff_fcmtoken_save,name="staff_fcmtoken_save"),
    path('staff_all_notification',staffviews.staff_all_notification,name="staff_all_notification"),
    # path('staff_notifications',staffviews.staff_notifications,name="staff_notifications"),
    path('staff_add_result',staffviews.staff_add_result,name="staff_add_result"),
    path('result_save',staffviews.result_save,name="result_save"),
    path('read_save',staffviews.read_save,name="read_save"),
    path('clear_all_staff',staffviews.clear_all_staff,name="clear_all_staff"),
    path('clear_one_staff',staffviews.clear_one_staff,name="clear_one_staff"),
    path('edit_student_result',EditResultViewClass.as_view(),name="edit_student_result"),
    path('fetch_student_result',staffviews.fetch_student_result,name="fetch_student_result"),
    # path('delete_not/<int:id>',staffviews.delete_not,name="delete_not"),
    path('start_live_classroom',staffviews.start_live_classroom, name="start_live_classroom"),
    path('start_live_classroom_process',staffviews.start_live_classroom_process, name="start_live_classroom_process"),
    path('firebase-messaging-sw.js',views.showFirebaseJS,name="show_firebase_js"),

    # student urls
    path('student_home', student_views.student_home, name="student_home"),
    path('student_view_attendance', student_views.student_view_attendance, name="student_view_attendance"),
    path('student_view_attendance_save', student_views.student_view_attendance_save, name="student_view_attendance_save"),
    path('student_apply_leave', student_views.student_apply_leave, name="student_apply_leave"),
    path('student_apply_leave_save', student_views.student_apply_leave_save, name="student_apply_leave_save"),
    path('student_feedback', student_views.student_feedback, name="student_feedback"),
    path('student_feedback_save', student_views.student_feedback_save, name="student_feedback_save"),
    path('student_profile',student_views.student_profile,name="student_profile"),
    path('Units',student_views.Units,name="Units"),
    path('student_profile_save',student_views.student_profile_save,name="student_profile_save"),
    path('student_fcmtoken_save',student_views.student_fcmtoken_save,name="student_fcmtoken_save"),
    path('student_all_notification',student_views.student_all_notification,name="student_all_notification"),
    path('student_view_result',student_views.student_view_result,name="student_view_result"),
    path('unit_registration',student_views.unit_registration,name="unit_registration"),
    path('get_units',student_views.get_units,name="get_units"),
    # path('units',student_views.units,name="units"),
    path('get_results',student_views.get_results,name="get_results"),
    path('resit',student_views.resit,name="resit"),
    path('read_save_student',student_views.read_save_student,name="read_save_student"),
    path('clear_all',student_views.clear_all,name="clear_all"),

Student/forms.py
from random import choices
from django import forms
from django.forms import ChoiceField, PasswordInput, EmailInput, TextInput
from requests import request

from Student.models import courses, students, sessionmodel, subject, hod


class DateInput(forms.DateInput):
    input_type = "date"


class ChoiceNoValidation(ChoiceField):
    def validate(self,value):
        pass

class EditStudentForm(forms.Form):
    email = forms.CharField(label="Email/Phone", max_length=50, widget=forms.TextInput(attrs={"class": "form-control","autocomplete":"off"}),required=False)
    first_name = forms.CharField(label="Firstname", max_length=50,
                                 widget=forms.TextInput(attrs={"class": "form-control"}))
    last_name = forms.CharField(label="Lastname", max_length=50,
                                widget=forms.TextInput(attrs={"class": "form-control"}))
    username = forms.CharField(label="Admission No", max_length=50,
                                widget=forms.TextInput(attrs={"class": "form-control","autocomplete":"off"}))
    address = forms.CharField(label="Address", max_length=50, widget=forms.TextInput(attrs={"class": "form-control"}),required=False)
    course_list=[]
    try:
        course = courses.objects.all()
        for course in course:
            small_course = (course.id, course.course_name)
            course_list.append(small_course)
    except:        
        course_list = []

    session_list = []
    try:
        sessions = sessionmodel.objects.all()
        for ses in sessions:
            small_ses = (ses.id, str(ses.session_start_year)+"  TO  "+str(ses.session_end_year))
            session_list.append(small_ses)
    except:    
        session_list = []

    gender_choice = (
        ('Male',"Male"),
        ('Female',"Female")
    )
    course = forms.ChoiceField(label="Course", choices=course_list,
                               widget=forms.Select(attrs={"class": "form-control"}))
    session_year_id = forms.ChoiceField(label="Session Year", widget=forms.Select(attrs={"class": "form-control"}),choices=session_list)
    profile_pic = forms.FileField(label="Profile Pic", max_length=50,
                                  widget=forms.FileInput(attrs={"class": "form-control"}), required=False)


class EditResultForm(forms.Form):
    def __init__(self,*args, **kwargs):
        self.staff_id=kwargs.pop("staff_id")
        super(EditResultForm,self).__init__(*args,**kwargs)

        subject_list=[]
        try:
            subjects=subject.objects.filter(staff_id=self.staff_id)
            for Subject in subjects:
                subjects_single=(Subject.id,Subject.code)
                subject_list.append(subjects_single)
        except:
            subject_list=[] 
        self.fields['subject_id'].choices=subject_list

    session_list=[]
    try:
        sessions=sessionmodel.objects.all()
        for session in sessions:
            session_single=(session.id,str(session.session_start_year)+" TO "+str(session.session_end_year))
            session_list.append(session_single)
    except:
        session_list=[]        

    subject_id=forms.ChoiceField(label="Subject",widget=forms.Select(attrs={"class":"form-control"}))       
    session_ids=forms.ChoiceField(label="Session Year",choices=session_list,widget=forms.Select(attrs={"class":"form-control"}))
    student_ids=ChoiceNoValidation(label="Student",widget=forms.Select(attrs={"class":"form-control"})) 
    assignment_marks=forms.CharField(label="Assignment Marks",widget=forms.TextInput(attrs={"class":"form-control"})) 
    exam_marks=forms.CharField(label="Exam Marks",widget=forms.TextInput(attrs={"class":"form-control"}))


class EditProfile(forms.Form):
    email = forms.CharField(label="Email/Phone", max_length=50, widget=forms.TextInput(attrs={"class": "form-control","autocomplete":"off","disabled":"disabled"}),required=False)
    first_name = forms.CharField(label="Firstname", max_length=50,
                                 widget=forms.TextInput(attrs={"class": "form-control","disabled":"disabled"}),required=False)
    last_name = forms.CharField(label="Lastname", max_length=50,
                                widget=forms.TextInput(attrs={"class": "form-control","disabled":"disabled"}),required=False)
    username = forms.CharField(label="Username", max_length=50,
                               widget=forms.TextInput(attrs={"class": "form-control","autocomplete":"off","disabled":"disabled"}),required=False)
    password = forms.CharField(label="Id Number", max_length=50,
                               widget=forms.TextInput(attrs={"class": "form-control", "autocomplete": "off","placeholder":"Only Fill if you want to change your password"}),required=False)
    profile_pic = forms.FileField(label="Profile Pic", max_length=50,
                                  widget=forms.FileInput(attrs={"class": "form-control"}), required=False)

templates/staff_template/Notifications.html
{% extends 'staff_template/base_template.html' %}
{% load static %}
{% block main_content %}
<section class="content">
      <div class="container-fluid">
       <div class="row">
          <div class="col-6">
            <div class="card card-primary">
              <div class="card-header">
                    <h3 class="card-title">Notifications</h3>
                    <div class="card-tools">
                        <form method="POST" action="/clear_all_staff" role="form">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-sm btn-danger">Clear All</button>
                        </form>
                    </div>
                </div>
              <div class="card-body table-responsive p-0">
                <table class="table table-hover text-nowrap">
                  <thead>
                    <tr>
                      <th>Message</th>
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                  {% for notification in notify %}
                    <tr>
                      <td>{{ notification.message }}</td>
                      <td>
                          <form method="POST" action="/clear_one_staff" role="form">
                            {% csrf_token %}
                              <input type="hidden" value="{{ notification.id }}" name="notification">
                            <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                          </form>
                      </td>
                    </tr>
                  {% endfor %}
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
              <div class="card-footer">
                      <div class="pagination">
                          <span class="step-links">
                              <span class="current">
                                   Page  {{ page_obj.number }}  of  {{ page_obj.paginator.num_pages }}.
                              </span>
                          </span>
                      </div>
                      {% if notify.has_other_pages %}
                                <ul class="pagination float-right">
                                    {% if notify.has_previous %}
                                        <li class="paginate_button page-item"><a class="page-link" href="?page={{ notify.previous_page_number }}" data-dt-idx="0" tabindex="0">Previous</a></li>
                                    {% else %}
                                        <li class="paginate_button page-item disabled"><a class="page-link" href="#" >Previous</a></li>
                                    {% endif %}
                                    {% for i in page_range|default_if_none:notify.paginator.get_elided_page_range %}
                                        {% if page_obj.number == i %}
                                            <li class="paginate_button page-item active"><a class="page-link">{{ i }}<span class="sr-only">(current)</span></a></li>
                                        {% else %}
                                            {% if i == page_obj.paginator.ELLIPSIS %}
                                                <li class="paginate_button page-item"><a class="page-link" href="#">{{ i }}</a></li>
                                            {% else %}
                                                <li class="paginate_button page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                                            {% endif %}
                                        {% endif %}
                                    {% endfor %}
                                    {% if notify.has_next %}
                                      <li class="page-item"><a class="page-link" href="?page={{ notify.next_page_number }}" >Next</a></li>
                                    {% else %}
                                      <li class="page-item disabled"><a class="page-link" href="#" >Next</a></li>
                                    {% endif %}
                                </ul>
                      {% endif %}
            </div>
            </div>
            <!-- /.card -->
          </div>
        </div>
      </div><!-- /.container-fluid -->
</section>
    <!-- /.content -->
{% endblock main_content %}

templates/staff_template/add_result.html
{% extends 'staff_template/base_template.html' %}
{% block custom_css %}
<style>
    .success{
        list-style:none;
        background-color:#008000;
        color:white;
        box-shadow:12px 12px 12px #0000ff;
        text-align:center
}
.error{
        list-style:none;
        background-color:#ff0000;
        color:white;
        box-shadow:12px 12px 12px #0000ff;
        text-align:center
}
</style>
{% endblock custom_css %}
{% load static %}
{% block main_content %}

<section class="content">
      <div class="container-fluid">
          {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                      <li {% if message.tags %} class="{{message.tags}}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
          {% endif %}
        <div class="row">
          <div class="col-md-6">
            <!-- general form elements -->
           <form action="{% url 'result_save' %}" method="post">
              {% csrf_token %}
              <div class="card card-warning">
                  <div class="card-header">
                      <h3 class="card-title">Add Results</h3>
                  </div>
                  <div class="card-body">
                    <div class="form-group">
                      <label>Subject</label>
                      <select class="form-control"  name="subjects" id="subjects">
                          {% for subjects in subjects %}
                            <option value="{{ subjects.id }}">{{ subjects.code }}</option>
                          {% endfor %}
                      </select>
                    </div>
                    <div class="form-group">
                      <label>Session Year</label>
                      <select class="form-control"  name="session_year" id="session_year">
                          {% for session_year in session_years %}
                            <option value="{{ session_year.id }}">{{ session_year.session_start_year }} TO {{ session_year.session_end_year }}</option>
                          {% endfor %}
                      </select>
                    </div>
                  </div>
                  <!-- /.card-body -->

                  <div class="card-footer">
                    <button type="button" class="btn btn-primary btn-block " id="fetch_student">Fetch Student</button>
                  </div>
                  <div id="student_data" class="card-footer" ></div>
              </div>
           </form>
          </div>
        </div>
            <!-- /.card -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
{% endblock main_content %}
{% block custom_js %}
<script>
  $(document).ready(function(){
    $("#fetch_student").click(function(){
      var subject=$("#subjects").val();
      var session_year=$("#session_year").val();


      $.ajax({
        url:'{% url 'get_student' %}',
        type:'POST',
        data:{subjects:subject,session_year:session_year},
      })
      .done(function(response){
        var json_data=JSON.parse(response);
        console.log(json_data)
        var div_data="<div class='form-group'><label>Student List:</label><select class='student_list form-control' name='student_list'>";
        for(key in json_data)
        {
          div_data+="<option value='"+json_data[key]['id']+"'>#ID: "+json_data[key]['id']+" : "+json_data[key]['name']+"</option>";
        }
        div_data+="</select>";
        div_data+="</div>";
        div_data+="<div class='form-group'><div class='row'>";
        div_data+="<div class='col-lg-6'>";  
        div_data+="<label>Assignment Marks: </label><input type='text' name='assignment' class='form-control' value='0' placeholder='Assignment marks'>";
        div_data+="</div>";  
        div_data+="<div class='col-lg-6'>";
        div_data+="<label> Exam Marks: </label><input type='text' name='exam_marks' class='form-control' value='0' placeholder='Exam marks'>";
        div_data+="</div>"; 
        div_data+="</div></div>"; 
        div_data+="<div class='form-group'>";
        div_data+="<button id='save_attendance' class='btn btn-success btn-block' type='submit' >Save Result</button>";
        div_data+="</div>";
        $("#student_data").html(div_data);
      })
      .fail(function(){
      swal.fire({
      text:"error in fetching student",
      icon:"error"
      }).then(() => {
            location.reload()
      })
      });
  });
})
  
</script>
{% endblock custom_js %}

templates/staff_template/edit_student_result.html
{% extends 'staff_template/base_template.html' %}
{% block custom_css %}
<style>
    .success{
        list-style:none;
        background-color:#008000;
        color:white;
        box-shadow:12px 12px 12px #0000ff;
        text-align:center
}
.error{
        list-style:none;
        background-color:#ff0000;
        color:white;
        box-shadow:12px 12px 12px #0000ff;
        text-align:center
}
</style>
{% endblock custom_css %}
{% load static %}
{% block main_content %}

<section class="content">
      <div class="container-fluid">
          {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                      <li {% if message.tags %} class="{{message.tags}}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
          {% endif %}
        <div class="row">
          <div class="col-md-8">
            <!-- general form elements -->
           <form action="{% url 'edit_student_result' %}" method="post">
              {% csrf_token %}
              <div class="card card-primary">
                  <div class="card-header">
                      <h3 class="card-title"> Edit Results </h3>
                  </div>
                <div class="card-body">
                    {{ form }}
                  <div class="card-footer">
                    <button type="submit" class="btn btn-primary btn-block " id="fetch_student">Update Result</button>
                  </div>
              </div>
           </form>
          </div>
        </div>
            <!-- /.card -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
{% endblock main_content %}
{% block custom_js %}
<script>
  $(document).ready(function(){
      fetchstudents();
      $("#id_subject_id").change(function(){
        fetchstudents();
        result_fetch_student();
    });
    $("#id_session_ids").change(function(){
      fetchstudents();
    });
    $("#id_student_ids").change(function(){
      result_fetch_student();
    });
    function fetchstudents(){
      var subject=$("#id_subject_id").val();
        var session_year=$("#id_session_ids").val();
        $.ajax({
          url:'{% url 'get_students' %}',
          type:'POST',
          data:{subjects:subject,session_year:session_year},
        })
        .done(function(response){
          var json_data=JSON.parse(response);
          console.log(json_data)
          var div_data="";
          for(key in json_data)
          {
            div_data+="<option value='"+json_data[key]['id']+"'>ID : "+json_data[key]['id']+" : "+json_data[key]['name']+"</option>";
          }
          $("#id_student_ids").html(div_data);
        })
        .fail(function(){
        swal.fire({
        text:"error in fetching student",
        icon:"error",
        }).then(() => {
            location.reload()
        })
        });
    }
    function result_fetch_student(){
      var id_student_ids=$("#id_student_ids").val();
        var subject=$("#id_subject_id").val();
        $.ajax({
          url:'{% url 'fetch_student_result' %}',
          type:'POST',
          data:{subject_id:subject,student_id:id_student_ids},
        })
        .done(function(response){
          if (response=="False"){
            swal.fire({
            text:"Result Not Found",
            icon:"info",
            })
          }else{
            var json_data=JSON.parse(response);
            $("#id_assignment_marks").val(json_data['assign_marks'])
            $("#id_exam_marks").val(json_data['exam_marks'])
          }
        })
        .fail(function(){
        swal.fire({
        text:"error in fetching student",
        icon:"error",
        }).then(() => {
            location.reload()
        })
        });
    }
})

</script>
{% endblock custom_js %}

templates/staff_template/registered_units.html
{% block page_title %} {% endblock page_title %}
{% load static %}
{% load i18n %}
{% block custom_css %}
<style>
    h1
    {
        padding-left:15;
        font-weight: italic;
        font-family: Georgia;
    }
    .school
    {
        padding-left:15;
        font-weight: bold;
    }
</style>
{% endblock custom_css %}
{% block main_content %}
<section class="content">
      <div class="row">
        <div class="col-lg-12">
          <div class="card">
           <div class="card-body">
             <table class="table" style="text-bold" width="100%">
                 <tr>
                     <td colspan="3"><h1><div class="school">SAMILSON SCHOOL</div></h1></td>
                 </tr>
                 <tr>
                     <td colspan="3" style="padding-left:10.5;font-size:11px">+254-74-0400114</td>
                 </tr>
                 <tr>
                     <td colspan="3" style="padding-left:9.4;font-size:11px;padding-bottom:.4;">samwelmilson@gmail.com</td>
                 </tr>
                 <tr>
                     <td colspan="3"><u><h1>Registered Students</h1></u></td>
                 </tr>
                 <tr>
                     <td style="font-weight:bold;padding-bottom:.2;padding-top:.2;font-size:13px;" width="60px">School:</td>
                     <td style="font-size:12px;padding-top:.2;padding-bottom:.2;">{{ Hod.dept_id.school_id.school_name }}</td>
                 </tr>
                 <tr>
                     <td style="font-weight:bold;padding-bottom:.2;padding-top:.2;font-size:13px;" width="90px">Department:</td>
                     <td style="font-size:12px;padding-top:.2;padding-bottom:.2;">{{ Hod.dept_id.dept_name }}</td>
                 </tr>
                 <tr>
                     <td style="font-weight:bold;padding-bottom:.2;padding-top:.2;font-size:13px;" width="90px">Subject Name:</td>
                     <td style="font-size:12px;padding-top:.2;padding-bottom:.2;">{{ subject_id.subject_name }}</td>
                 </tr>
             </table>
             <table class="table" border="1" width="70%" style="height:auto;">
                <thead>
                    <tr>
                      <th width="100px" align="left" style="padding-top:.2;font-size:12px;padding-left:.2;"><u> Reg NO</u></th>
                      <th width="100px" align="left" style="padding-top:.2;font-size:12px;padding-left:.2;"><u>Name</u></th>
                      <th width="100px" align="left" style="padding-top:.2;font-size:12px;padding-left:.2;"><u>Signature</u></th>
                    </tr>
                </thead>
                <tbody>
                    {% for student in student %}
                      <tr>
                          <td width="100px" style="padding-top:.2;font-size:12px;padding-left:.2;">{{ student.student_id.username }}</td>
                          <td width="300px" style="padding-top:.2;font-size:12px;padding-left:.2;">{{ student.student_id.first_name }}&nbsp;{{ student.student_id.last_name }}</td>
                          <td></td>
                      </tr>
                    {% endfor %}
                </tbody>
             </table>
           </div>
          </div>
        </div>
      </div>
</section>
{% endblock main_content %}